import { test, expect, seedAuth, BACKEND } from './_fixtures';
import { apiDeleteTestSetByName, uniq } from './_api';
import type { APIRequestContext } from '@playwright/test';

/**
 * Traces — filtering and "Add to Test Set" against the live backend. A trace is
 * generated by executing a prompt through the model, so these tests are skipped
 * without DEEPSEEK_API_KEY.
 */
const HAS_MODEL_KEY = !!process.env.DEEPSEEK_API_KEY;

/** Execute a prompt synchronously → produces one trace; returns its messageId. */
async function generateTrace(api: APIRequestContext, purpose: string): Promise<string> {
  const res = await api.post(`${BACKEND}/data/v1.0/admin/llm/prompt/message/sync`, {
    data: {
      promptIds: [{ promptId: 'playground', prompt: 'Reply with one word: PONG' }],
      variables: {},
      language: 'GENERAL',
      purpose,
    },
  });
  expect(res.ok(), `sync execution failed: ${res.status()}`).toBeTruthy();
  return (await res.json()).data.messageId;
}

test.describe('Traces', () => {
  test.skip(!HAS_MODEL_KEY, 'DEEPSEEK_API_KEY not set — trace generation needs the model');

  test('search by message id shows the matching trace', async ({ page, request }) => {
    const messageId = await generateTrace(request, uniq('e2e-trace'));

    await seedAuth(page);
    await page.goto('traces');
    await page.waitForLoadState('networkidle');

    await page.getByPlaceholder('Message ID').fill(messageId);
    await page.locator('button:has(.pi-search)').first().click();

    await expect(page.locator('.group-header')).toHaveCount(1, { timeout: 10_000 });
    await expect(page.locator('body')).toContainText(messageId.substring(0, 12));
  });

  test('changing the time range refetches without crashing', async ({ page, request }) => {
    await generateTrace(request, uniq('e2e-trace'));

    await seedAuth(page);
    await page.goto('traces');
    await page.waitForLoadState('networkidle');

    const refetch = page.waitForResponse((r) => r.url().includes('/analytics/traces') && r.ok());
    await page.getByRole('button', { name: '1W', exact: true }).click();
    await refetch;
    await expect(page.locator('body')).not.toContainText(/uncaught|application error/i);
  });

  test('add a trace to a new test set via the UI', async ({ page, request }) => {
    page.on('dialog', (d) => d.accept().catch(() => {})); // native success alert
    const messageId = await generateTrace(request, uniq('e2e-trace'));
    const tsName = uniq('e2e-traceset');

    try {
      await seedAuth(page);
      await page.goto('traces');
      await page.waitForLoadState('networkidle');

      // Narrow to our trace, select its group, open the modal.
      await page.getByPlaceholder('Message ID').fill(messageId);
      await page.locator('button:has(.pi-search)').first().click();
      await expect(page.locator('.group-header')).toHaveCount(1, { timeout: 10_000 });
      await page.locator('.group-header .p-checkbox').first().click();

      await page.getByRole('button', { name: /add .* to test set/i }).click();
      await expect(page.locator('.p-dialog')).toBeVisible();
      // Leave the dropdown empty → the inline "new test set" form appears.
      await page.getByPlaceholder('New test set name').fill(tsName);

      const added = page.waitForResponse((r) =>
        /\/admin\/test-sets\/[^/]+\/items$/.test(r.url()) && r.request().method() === 'POST' && r.ok(),
        { timeout: 15_000 });
      await page.locator('.p-dialog').getByRole('button', { name: /^add to test set$/i }).click();
      await added;

      // Verify server-side: a test set with that name now holds one item.
      const sets = await request.get(`${BACKEND}/data/v1.0/admin/test-sets`);
      const set = ((await sets.json()) as Array<{ id: string; name: string }>).find((t) => t.name === tsName);
      expect(set, 'the new test set should exist').toBeTruthy();
      const items = await request.get(`${BACKEND}/data/v1.0/admin/test-sets/${set!.id}/items`);
      const body = await items.json();
      const list = Array.isArray(body) ? body : body.data;
      expect(list.length, 'test set should have 1 item after add').toBeGreaterThanOrEqual(1);
    } finally {
      await apiDeleteTestSetByName(request, tsName);
    }
  });
});
