Args = --no-fallback \
       --enable-url-protocols=https \
       -H:+ReportExceptionStackTraces \
       -H:ReflectionConfigurationFiles=${.}/reflect-config.json \
       -H:ResourceConfigurationFiles=${.}/resource-config.json \
       --initialize-at-build-time=org.slf4j.LoggerFactory,ch.qos.logback \
       --initialize-at-run-time=org.apache.maven.model.io.xpp3.MavenXpp3Reader,org.apache.maven.model.io.xpp3.MavenXpp3Writer